############################################################
# DEVine
#
# rEFInd Theme by Debraj Kundu
# The Theme is With a Dark / Night Attribute
############################################################
scanfor internal,external,netboot,manual

# Load banner / background and fit to screen
banner themes/rEFInd-DEVine/extra/background/12970447.png
banner_scale fillscreen

# Load icons
big_icon_size 256
small_icon_size 64
icons_dir themes/rEFInd-DEVine/icons

# Load selectors
selection_big themes/rEFInd-DEVine/extra/selections/selection_big.png
selection_small themes/rEFInd-DEVine/extra/selections/purple/selection_small.png

# Stop auto booting
timeout 0

# set resolution to maximum available
# resolution 1920 1080
resolution max

# Enable Mouse Support
enable_mouse
mouse_size 24

# Enable Graphics
use_graphics_for linux,grub,osx,windows

# Tools
also_scan_tool_dirs +,EFI/tools/MemTest86,EFI/tools/edk2

# EFI Scan DIRs
also_scan_dirs +,@/boot/efi,@/kernels,@arch/boot

write_systemd_vars true
